// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Coin struct {
	MintAddress *string  `json:"mintAddress,omitempty"`
	MarketCap   *float64 `json:"marketCap,omitempty"`
	Name        *string  `json:"name,omitempty"`
}

type Query struct {
}
